name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest       
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: test
        run: |
          xcrun simctl list
          xcodebuild test -project TestActionsSwift.xcodeproj -scheme TestActionsSwift -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X'
