name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest       
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: test
        run: |
          xcodebuild clean test -project TestActionsSwift.xcodeproj -scheme TestActionsSwiftTests -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4'

